### ISSUE TITLE
Fails to install in virtual env

### ISSUE THREAD

**Issue by mih** [AdinaWagner/multimatch#8]
Not sure what is happening, yet. Running the following in a fresh clone:

```
mih@meiner /tmp/multimatch (git)-[master] % virtualenv --python=python3 ~/env/multimatch
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/mih/env/multimatch/bin/python3
Also creating executable in /home/mih/env/multimatch/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
mih@meiner /tmp/multimatch (git)-[master] % . ~/env/multimatch/bin/activate
(multimatch) mih@meiner /tmp/multimatch (git)-[master] % pip install -e .
Obtaining file:///tmp/multimatch
    Complete output from command python setup.py egg_info:
    WARNING: pypandoc failed to import or threw an error while converting README.md to RST: ModuleNotFoundError("No module named 'pypandoc'",)  .md version will be used as is
    running egg_info
    creating multimatch.egg-info
    writing multimatch.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/multimatch/setup.py", line 62, in <module>
        "Operating System :: OS Independent",
      File "/home/mih/env/multimatch/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/mih/env/multimatch/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 289, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/home/mih/env/multimatch/lib/python3.6/site-packages/setuptools/command/egg_info.py", line 620, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/lib/python3.6/distutils/dist.py", line 1106, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/home/mih/env/multimatch/lib/python3.6/site-packages/setuptools/dist.py", line 163, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/usr/lib/python3.6/distutils/util.py", line 474, in rfc822_escape
        lines = header.split('\n')
    AttributeError: 'builtin_function_or_method' object has no attribute 'split'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/multimatch/
```

**Comment by mih** [comment]
Here is the fix:

```diff
diff --git a/setup.py b/setup.py
index f4419f4..26dba95 100755
--- a/setup.py
+++ b/setup.py
@@ -27,7 +27,7 @@ except (ImportError, OSError) as exc:
         "WARNING: pypandoc failed to import or threw an error while converting"
         " README.md to RST: %r  .md version will be used as is" %exc
     )
-    long_description = open(README).read
+    long_description = open(README).read()
 
 # Metadata
 setup(
```

**Comment by AdinaWagner** [comment]
Thx so much for noticing and finding the problem!
